name: LaTex package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual execution'

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: Compile Latex file
    steps:
    - uses: actions/checkout@v1
    - name: Compilation
      uses: subhalingamd/tex-compile-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tex_path: 'Hugo_Arganda_Resume.tex'
        push: 'yes'
