name: Generate PDF (texlive)

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile
      run: make

    - name: Commit PDF
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Commitobot
          author_email: my@mail.com
          message: "Updating build result!"
          add: "pdf/test.pdf"

    - uses: actions/upload-artifact@v2
      with:
        name: resume
        path: pdf/*.pdf

        