name: Generate PDF (texlive)

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile
      run: make

    - uses: actions/upload-artifact@v2
      with:
        name: Upload PDF
        path: pdf/*.pdf

    - name: Commit PDF
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Hugo Arganda
          author_email: hugo.arganda@gmail.com
          message: "Upload PDF"
          add: "pdf/*.pdf"