name: Generate PDF (texlive)

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile
      run: make

    - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: '*.pdf'
          cwd: './pdf/'
        